### PR TITLE
Add upload functionality based on the existing download json

### PR DESCRIPTION
**Pull request by royteeuwen**

### CODE REVIEW

**Comment by royteeuwen** [comment]
example

**Comment by serverTimeout01** [comment]
thanks for the contribution. I will have a look at it later. In the bigger picture, we will probably try to move / incorporate this into the Library Action Panel with a list of saved dialogs, so that the upload not necessarily override the current one as well. But in the meantime it's really nice to even have the feature 👍

**Comment by royteeuwen** [comment]
Sounds logical, it would also be easier / handier if the upload / download would be through the granite dialog xml, but this was a bit more work and I wanted something to start with ;)!

**Comment by serverTimeout01** [comment]
Just did some minor changes:

- ESLint cleanup
- Move CSS to Footer CSS
- semantically corrected separator markup change (HR)
- adjusted footer layout to compensate additional button

we will do some further refactoring once we attempt to implement the Library Action Panel.
Thanks again for the contribution. I will merge this now.

**Pull request merged**
